[WIP] Upgrade docker, dnsdock and move from ui-for-docker to portainer
yappabe/vagrant-docker pull request #17
Opened 2017-06-06 13:40 UTC by jverdeyen

# How to upgrade

## Upgrade repo

```
git pull
vagrant box update
```

## Reload vagrant

```
vagrant reload
```

## Remove old containers

```
docker kill uifd-ui-for-docker
docker rm -v uifd-ui-for-docker
docker kill ailispaw-dnsdock
docker rm -v ailispaw-dnsdock
```

## Provision with new containers

```
vagrant provision
```

## Upgrade locale packages.

* docker-compose —> ^1.13.0
* docker  —>  ^17.05.0
```
brew upgrade docker-compose 
brew upgrade docker
```

# Docker Compose v3

After this you can upgrade your `docker-compose.yml`.

## Example

```
version: '3'

services:
    nginx:
        image: yappabe/nginx:1.9
        volumes:
            - ./docker/shared/:/shared
            - ./:/var/www/app
        depends_on:
            - php
        env_file: 'app/config/.env'
        environment:
            DNSDOCK_ALIAS: project.docker.webfolks.be, admin.project.docker.webfolks.be

    mysql:
        image: mariadb:10
        env_file: 'app/config/.env'
        environment:
            DNSDOCK_ALIAS: mysql.project.docker.webfolks.be

    php:
        image: yappabe/php:7.1
        volumes:
            - ./docker/shared/:/shared
            - ./:/var/www/app
            - vendor:/vendor
        links:
            - mysql
        working_dir: /var/www/app
        env_file: 'app/config/.env'
        depends_on:
            - mysql
            - mailcatcher

    mailcatcher:
        image: yappabe/mailcatcher
        environment:
            DNSDOCK_ALIAS: mailcatcher.project.docker.webfolks.be

volumes:
  vendor:
```

## .env

A .env file can look like this

```
DOCUMENT_ROOT=/var/www/app/web
INDEX_FILE=app_dev.php
PHP_FPM_SOCKET=php:9000
MYSQL_ROOT_PASSWORD=dev
MYSQL_DATABASE=project
MYSQL_USER=root
MYSQL_HOST=mysql
MYSQL_PORT=3306
PHP_FPM_USER=root
PHP_ERROR_REPORTING=E_ALL
HISTFILE=/shared/.bash_history
MAILER_TRANSPORT=smtp
MAILER_HOST=mailcatcher
MAILER_USER=null
MAILER_PASSWORD=null
MAILER_PORT=1025
MAILER_SECURITY=null
```

2017-06-07 09:12 UTC, wesleylancel approved these changes

2017-06-07 12:00 UTC, veloxy approved these changes
Seems to be working properly!

2017-06-12 10:02 UTC, jverdeyen commented
Will update README for v3

2017-06-15 10:55 UTC, veloxy requested changes

2017-06-15 10:55 UTC, veloxy commented on Vagrantfile
> +$docker_version = "latest"
Should we really set this to latest again? Check #7 where we decided not to.

2017-06-15 10:59 UTC, veloxy approved these changes

2017-06-15 11:00 UTC, merged